name: env_wsi
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bottleneck=1.3.4
  - ca-certificates=2022.6.15
  - freetype=2.10.4
  - giflib=5.2.1
  - joblib=1.1.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.5
  - libdeflate=1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mkl=2022.1.0
  - ncurses=6.3
  - ninja=1.11.0
  - numexpr=2.8.0
  - numpy=1.21.6
  - openjpeg=2.4.0
  - openssl=3.0.4
  - pip=22.1.2
  - pthread-stubs=0.4
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2022.1
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=62.6.0
  - six=1.16.0
  - sqlite=3.38.5
  - tbb=2021.5.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchvision=0.5.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - histolab==0.5.1
    - imageio==2.19.3
    - networkx==2.6.3
    - openslide-python==1.2.0
    - packaging==21.3
    - pandas==1.3.5
    - pillow==8.4.0
    - pyparsing==3.0.9
    - pywavelets==1.3.0
    - scikit-image==0.19.2
    - tifffile==2021.11.2
    - typing-extensions==4.2.0
